language: python

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.6"

install:
   - source circleci/travis_install.sh
   - ipython kernel install --user --name testkernel
   - jupyter kernelspec list

script:
  - shopt -s globstar
  - for cpy in **/*.py; do
    if [[ $cpy = *"Kaggle"* ]]; then
        echo "skipping kaggle kernel $cpy";
    else
      python $cpy |& tee nb_to_md.txt;
      traceback=$(grep "Traceback (most recent call last):" nb_to_md.txt);
      if [[ $traceback ]]; then
          exit 1;
      fi;
    fi;
    done
